<?php $this->placeholder('heading')->set("Backlog for Project " . $this->project->getName()); ?>

<div id="backlogcontainer">

    <div id="projectsummary" class="north">

        <h2>Project Summary</h2>
        <p>Product Owner: <?php echo $this->project->getProductOwner()->getName(); ?></p>

    </div>

    <div id="backlogs" class="center">

        <div id="currentsprint">
            <h2>Current Sprint</h2>
        </div>

        <div id="sprints">
            <h2>Upcoming Sprints</h2>
        </div>

        <div id="backlog">

            <h2>Backlog</h2>
            <?php $this->headScript()->captureStart() ?>
            $(function() {
                $('#addStory').button();
            });
            <?php $this->headScript()->captureEnd() ?>
            <div id="paragraphs" class="block" style="margin-bottom: 5px">
            <a id="addStory" href="<?php echo $this->url(array('controller' => 'story', 'action' => 'add', 'project' => $this->project->getId()), null, true); ?>">Add Story</a>
            </div>

            <div id="storylist">
                <?php foreach($this->project->getStories() as $story): ?>
                <div id="story_<?php echo $story->getId(); ?>">
                    <h3>
                        <span style="float: right; padding: 0.5em 0.5em 0 0;"><?php echo $story->getEstimatedPoints(); ?> SP</span>
                        <a href="#"><?php echo $story->getTitle(); ?></a>
                    </h3>
                    <div>

                        <p style="font-weight: bold;">
                        <?php echo nl2br($story->getDescription()); ?>
                        </p>

                        <p>Status: <?php echo $story->getState(); ?></p>

                        <?php if (count($story->getCriteria()) > 0): ?>

                        <p><strong>Acceptance Criteria</strong></p>

                        <table>
                            <colgroup>
                                <col style="width: 20px;"/>
                                <col />
                            </colgroup>
                            <tbody>
                            <?php foreach ($story->getCriteria() AS $criterion): ?>
                            <tr>
                                <td style="padding: 2px; vertical-align: middle;">
                                    <input
                                        class="criteria_accepted"
                                        id="criterion_<?php echo $criterion->getId(); ?>"
                                        type="checkbox"
                                        <?php if ($criterion->getIsAccepted()): ?>
                                        checked="checked"
                                        <?php endif; ?>
                                    />
                                </td>
                                <td style="padding: 2px; vertical-align: middle;"><?php echo $criterion->getCriterion(); ?></td>
                            </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>

                        <?php else: ?>
                        <p><strong>No Acceptance Criteria</strong></p>
                        <?php endif; ?>

                        <?php if ($story->hasComments()): ?>
                            <strong>Comments:</strong>
                            <?php foreach ($story->getComments() AS $comment): ?>
                            <div style="margin: 5px 0; background-color: #f0f0f0; padding: 3px;">
                                <div><?php echo nl2br($comment->getComment()); ?></div>
                                <div class="userinfo" style="float: none;">
                                    <?php echo $this->gravatar($comment->getCreatedBy()->getEmail(), '20'); ?>
                                    <?php echo $comment->getCreatedBy()->getName(); ?> at
                                    <?php echo $comment->getCreatedOn()->format('Y-m-d H:i:s'); ?>
                                </div>
                            </div>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <?php $this->headScript()->captureStart() ?>
                        $(function() {
                            $('.button').button();
                        });
                        <?php $this->headScript()->captureEnd() ?>
                        <a class="button" href="/story/add-comment/story/<?php echo $story->getId(); ?>">Add Comment</a>
                        <a class="button" href="/story/add-criterion/story/<?php echo $story->getId(); ?>">Add Acceptance Criterion</a>
                        <a class="button" href="<?php echo $this->url(array('controller' => 'story', 'action' => 'pdf-export', 'project' => $this->project->getId(), 'story' => $story->getId()), null, true);?>" target="_new">PDF export</a>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

        </div>

    </div>

</div>

<?php $this->headStyle()->captureStart(); ?>

    #backlogcontainer {
        width: 100%;
    }

    #currentsprint {
    }

    #sprints {
    }

    #backlog {
    }

    #projectsummary {
        widht: 100%;
        background-color: #DBDBDB;
        border: 1px solid black;
    }

    h2 {
        margin: 0;
        padding: 2px;
        background-color: black;
        color: white;
        font-size: 1.1em;
    }

<?php $this->headStyle()->captureEnd(); ?>
<?php $this->headScript()->captureStart() ?>

$(function() {

    $('#backlogcontainer').layout({
        type: 'border',
        resize: false
    });

    $('#backlogs').layout({
        type: 'grid',
        columns: 3,
        rows: 1,
        items: [
            $('#currentsprint'),
            $('#sprints'),
            $('#backlog')
        ]
    });

    $(".criteria_accepted").change(function(event) {
        var id = event.target.id;

        var checked = event.target.checked;

        var regex = /^criterion_(\d+)$/;
        var match = regex.exec(id);
        var id = match[1];

        var send = {criterion: id, checked: checked};
        $.post("/story/update-criterion", send, function(theResponse){
            console.debug("Criterion updated");
            console.debug(theResponse);
        });
    });

    var stop = false;
    $("#storylist h3").click(function(event) {
        if (stop) {
            event.stopImmediatePropagation();
            event.preventDefault();
            stop = false;
        }
    });
    $("#storylist").accordion({
        header: "> div > h3",
        collapsible: true,
        active: false,
        autoHeight: false
    }).sortable({
        axis: "y",
        handle: "h3",
        stop: function(event, ui) {
            stop = true;
        },
        update: function(event, ui) {
            var order = $('#storylist').sortable('serialize');
            $.post("/backlog/priorize", order, function(theResponse){
                console.debug("Sorting saved");
                console.debug(theResponse);
            });
        }
    });

    <?php if ($this->storyId > 0): ?>
    $('#storylist').accordion('activate', '#story_<?php echo $this->storyId; ?> > h3');
    <?php endif; ?>

});

<?php $this->headScript()->captureEnd() ?>