<?php $this->placeholder('heading')->set("Backlog for " . $this->project->getName()); ?>

<div class="grid_16">
    <div class="box">
        <h2>Project Summary</h2>
        <div id="paragraphs" class="block">
        <p>Product Owner: <?php echo $this->project->getProductOwner()->getName(); ?></p>
        </div>
    </div>
</div>
<div class="clear"></div>

<div class="grid_5">
    <div class="box">
        <h2>Current Sprint</h2>
    </div>
</div>
<div class="grid_5">
    <div class="box">
        <h2>Upcoming Sprints</h2>

    </div>
</div>
<div class="grid_6">
    <div class="box" style="padding-bottom: 10px">
        <h2>Backlog</h2>
        <?php $this->headScript()->captureStart() ?>
        $(function() {
            $('#addStory').button();
        });
        <?php $this->headScript()->captureEnd() ?>
        <div id="paragraphs" class="block" style="margin-bottom: 5px">
        <a id="addStory" href="<?php echo $this->url(array('controller' => 'story', 'action' => 'add', 'project' => $this->project->getId()), null, true); ?>">Add Story</a>
        </div>

        <div id="storylist">
            <?php foreach($this->project->getStories() as $story): ?>
            <div id="story_<?php echo $story->getId(); ?>">
                <h3>
                    <span style="float: right; padding: 0.5em 0.5em 0 0;"><?php echo $story->getEstimatedPoints(); ?> SP</span>
                    <a href="#"><?php echo $story->getTitle(); ?></a>
                </h3>
                <div>

                    <p style="font-weight: bold;">
                    <?php echo nl2br($story->getDescription()); ?>
                    </p>

                    <p>Status: <?php echo $story->getState(); ?></p>

                    <?php if ($story->hasComments()): ?>
                        <strong>Comments:</strong>
                        <?php foreach ($story->getComments() AS $comment): ?>
                        <div style="margin: 5px 0; background-color: #f0f0f0; padding: 3px;">
                            <div><?php echo nl2br($comment->getComment()); ?></div>
                            <div class="userinfo" style="float: none;">
                                <?php echo $this->gravatar($comment->getCreatedBy()->getEmail(), '20'); ?>
                                <?php echo $comment->getCreatedBy()->getName(); ?> at
                                <?php echo $comment->getCreatedOn()->format('Y-m-d H:i:s'); ?>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    <?php endif; ?>

                    <?php $this->headScript()->captureStart() ?>
                    $(function() {
                        $('.button').button();
                    });
                    <?php $this->headScript()->captureEnd() ?>
                    <a class="button" href="/story/add-comment/story/<?php echo $story->getId(); ?>">Add Comment</a>

                    <a class="button" href="<?php echo $this->url(array('controller' => 'story', 'action' => 'pdf-export', 'project' => $this->project->getId(), 'story' => $story->getId()), null, true);?>" target="_new">PDF export</a>

                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<div class="clear"></div>

<?php $this->headScript()->captureStart() ?>

$(function() {
    var stop = false;
    $("#storylist h3").click(function(event) {
        if (stop) {
            event.stopImmediatePropagation();
            event.preventDefault();
            stop = false;
        }
    });
    $("#storylist").accordion({
        header: "> div > h3",
        collapsible: true,
        active: false,
        autoHeight: false
    }).sortable({
        axis: "y",
        handle: "h3",
        stop: function(event, ui) {
            stop = true;
        },
        update: function(event, ui) {
            var order = $('#storylist').sortable('serialize');
            $.post("/backlog/priorize", order, function(theResponse){
                console.debug("Sorting saved");
                console.debug(theResponse);
            });
        }
    });

    <?php if ($this->storyId > 0): ?>
    $('#storylist').accordion('activate', '#story_<?php echo $this->storyId; ?> > h3');
    <?php endif; ?>
});

<?php $this->headScript()->captureEnd() ?>