<h1>Backlog</h1>
<p>
    <h2>Project: <?php echo $this->project->name?></h2>
    <p>Product Owner: <?php echo $this->project->getProductOwner()->getName(); ?></p>
    <a href="<?php echo $this->url(array('controller' => 'project'), null, true)?>">Back to projects</a>
</p>
<p>
    <ul>
    <?php foreach($this->project->getStories() as $story):?>
        <li><?php echo $story->getTitle(); ?> (<?php echo $story->getId(); ?>)
            <ul>
                <li>Story: <?php echo $story->getDescription(); ?></li>
                <li>Estimation: <?php echo $story->getEstimatedPoints(); ?></li>
                <li>Status: <?php echo $story->getState(); ?></li>
            </ul>
        </li>
    <?php endforeach?>
    </ul>
</p>