<?php $this->headStyle()->captureStart() ?>
    .userinfo .gravatar {
        border:1px solid #FFFFFF;
        margin-right:3px;
        margin-top:-3px;
        vertical-align:middle;
    }
    .userinfo {
        float: right;
        margin-right: 10px;
        margin-top: 10px;
    }

    html, body {
        width: 100%;
        height: 100%;
        padding: 0;
        margin: 0;
        overflow: hidden;
        font-size: 0.9em;
        font-family: Verdana, Arial, sans-serif;
    }

    .north, .south, .west, .east, .center {
        display: inline-block;
    }

    #header {
        height: 3em;
        background-color: #DBDBDB;
        border-bottom: 1px solid black;
    }

    #footer {
        height: 2em;
        background-color: #DBDBDB;
        border-top: 1px solid black;
        font-size: 0.65em;
        padding: 0.5em 2em;
    }

    #navigation {
        background-color: #C9C7C9;
        border-bottom: 1px solid black;
    }

    #content {
        padding: 10px;
    }

    #main {

    }

    #content {

    }

    #navigation ul {
        margin:0;
        padding:0;
        float:left;
        width:100%;
    }
    #navigation li {
        margin:0;
        padding:0 0 0 0.7em;
        list-style:none;
        float:left;
        margin:0 0 0 0;
    }
    #navigation li a {
        text-decoration:none;
        display:block;
        padding:0.3em 0.8em 0.3em 0;
        color:black;
    }
    #navigation li:hover {
        background-color: #C6BBC9;
    }
    #navigation li:hover a {

    }

    h1 {
        margin: 3px 0 3px 10px;
        font-size: 1.3em;
    }

<?php $this->headStyle()->captureEnd() ?>
<?php $this->headScript()->captureStart() ?>
$(function() {

    function layout() {
        $('body').layout({
            type: 'border',
            resize: false,
            hgap: 6
        });
    }

    // Then do the main layout.
    layout();

    $('#innerbordercontainer').layout({
        type: 'border',
        resize: false
    });

    $('#main').layout({
        type: 'border',
        resize: false
    });

    // Hook up the re-layout to the window resize event.
    $(window).resize(layout);

});
<?php $this->headScript()->captureEnd() ?>
<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>

    <div class="north" id="header">

        <div class="userinfo">
            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <?php $user = Zend_Auth::getInstance()->getIdentity(); ?>
            <?php echo $this->gravatar($user->getEmail(), 20); ?>
            <span style="font-size: 12px; font-weight: bold;">
                <?php echo $user->getName(); ?>
                |
                <a href="/user/logout">Logout</a>
            </span>
            <?php endif; ?>
        </div>

        <p id="title" style="margin: 0; padding: 5px 0 0 10px; font-size: 1.4em; font-weight: bold;">
            AgilePlanningTool
        </p>

        <div class="clear"></div>

    </div>

    <div class="center" id="innerbordercontainer">

        <div class="north" id="navigation">
            <?php echo $this->navigation()->menu()->setUlClass('nav main'); ?>
        </div>

        <div class="center" id="main">

            <h1 id="pageheading" class="north"><?php echo $this->placeholder('heading'); ?></h1>

            <div id="content" class="center">
            <?php echo $this->layout()->content ?>
            </div>

        </div>

    </div>

    <div class="south" id="footer">AgilePlanningTool on <a href="http://github.com/feibeck/AgilePlanningTool">Github</a></div>

</body>
</html>
