<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>
    <p>
        <a href="/">Home</a>
        <a href="/project">Projects</a>
        <a href="/user/logout">Logout</a>
    </p>
    <hr />
    <?php echo $this->layout()->content ?>
</body>
</html>
