<?php echo $this->doctype() ?>
    <?php $this->headStyle()->captureStart() ?>
    .userinfo .gravatar {
        border:1px solid #FFFFFF;
        margin-right:3px;
        margin-top:-3px;
        vertical-align:middle;
    }
    .userinfo {
        float: right;
        margin-right: 10px;
        margin-top: 10px;
    }
    <?php $this->headStyle()->captureEnd() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
</head>
<body>
    <div class="container_16">
        <div class="grid_16">
            <div class="userinfo">
                <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                <?php $user = Zend_Auth::getInstance()->getIdentity(); ?>
                <?php echo $this->gravatar($user->getEmail(), 20); ?>
                <span style="font-size: 12px; font-weight: bold;">
                    <?php echo $user->getName(); ?>
                    |
                    <a href="/user/logout">Logout</a>
                </span>
                <?php endif; ?>
            </div>
            <h1 id="branding">
                <a href="../../../">AgilePlanningTool (alpha)</a>
            </h1>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
        <div class="grid_16">
            <?php echo $this->navigation()->menu()->setUlClass('nav main'); ?>
        </div>
        <div class="clear"></div>
        <div class="grid_16">
            <h2 id="page-heading"><?php echo $this->placeholder('heading'); ?></h2>
        </div>
        <div class="clear"></div>
        <div class="grid_16" style="padding-bottom: 15px;">
            <?php echo $this->layout()->content ?>
        </div>
        <div class="clear"></div>
        <div class="grid_16" id="site_info">
            <div class="box">
                <p>AgilePlanningTool on <a href="http://github.com/feibeck/AgilePlanningTool">Github</a>.</p>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</body>
</html>
