<?php $this->placeholder('heading')->set("Backlog Management for Agile Projects"); ?>

<div class="grid_8">
    <div class="box">
        <h2>Welcome!</h2>
        <div id="paragraphs" class="block">
            <p>Welcome to the AgilePlanningTool!</p>
        </div>

    </div>
</div>

<div class="grid_8">
    <div class="box">
        <h2>Login</h2>
        <div class="block" id="forms">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
